### ISSUE TITLE
Issue in scraping pepperfry

### ISSUE THREAD

**Issue by VarunSrivastavaIITD** [vineetm/ell-881-2018-deep-learning#10]
On trying out the scrapy shell on the homepage 'https://www.pepperfry.com/', i.e. _"scrapy shell https://www.pepperfry.com/ --nolog"_ I get a 403 access denied response.

As suggested both on the [scrapy docs](https://doc.scrapy.org/en/latest/topics/practices.html#avoiding-getting-banned) as well as SO, this is probably due to **anti scraping** measures taken by the site. Can anyone please confirm if they are facing the same issue, since I assume getting around such measures wasn't the intention of the assignment?

P.S. _To ensure there was nothing wrong with my scrapy setup, I tried the same on other websites too, which gave no such problems._

**Comment by vineetm** [comment]
Addressed in vineetm/ell-881-2018-deep-learning#6
