### ISSUE TITLE
Extend the deadline 

### ISSUE THREAD

**Issue by varunsood189** [vineetm/ell-881-2018-deep-learning#44]
Respected Sir,

It's a sincere request to extend the deadline until after the Diwali break. Because we have a placement session in progress. It's taking all the time. That is why we are not able to concentrate on project 2. 
I also request all the students who are facing the same issue to comment under this issue to confirm my claim.

Regards,
Varun

**Comment by VDnarendra** [comment]
Yes sir, please consider extending the deadline. We have placement tests these days. But we are free from these tests in Diwali break. We can keep most of the time on project2 in those holidays.

**Comment by pushpendradahiya** [comment]
> Respected Sir,
> 
> It's a sincere request to extend the deadline until after the Diwali break. Because we have a placement session in progress. It's taking all the time. That is why we are not able to concentrate on project 2.
> I also request all the students who are facing the same issue to comment under this issue to confirm my claim.
> 
> Regards,
> Varun

+1 
Also, there are issues related to HPC quota. submission after the holidays will be good for both the cases.

**Comment by hareesh00** [comment]
+1

**Comment by sakshi18agrawal1** [comment]
> Respected Sir,
> 
> It's a sincere request to extend the deadline until after the Diwali break. Because we have a placement session in progress. It's taking all the time. That is why we are not able to concentrate on project 2.
> I also request all the students who are facing the same issue to comment under this issue to confirm my claim.
> 
> Regards,
> Varun

+1
It is difficult to manage both the things simultaneously.

**Comment by anshumitts** [comment]
+1

**Comment by utkarsh1097** [comment]
+1

**Comment by ishank1995** [comment]
+1

**Comment by varunsood189** [comment]
11/11/18 until next Sunday of the present deadline.

**Comment by raghavsi** [comment]
Please submit current work -- code, whatever results you have (in plots/table) on 11 Nov night.
You can submit a final report on 17 Nov night and be evaluated on that.
